### ISSUE TITLE
simpleDrawingApplication review

### ISSUE THREAD

**Issue by jasekiw** [micahpotts/jquery-apps#10]
The application performs well.
there is an issue though.

if you open up the developer console (f12)(windows) (Cmd + Opt + I)(Mac) and go to the console tab you will see hundreds of errors showing when hovering over the canvas. They stop when you click the canvas.

The issue is on line 7 where you declare 
`var mousedown = false;`
the rest of your application looks for a variable calles mouseDown (notice the capital D).
This causes the error "mouseDown is not defined" when trying to reference it.

The reason why the application works as expected is because you eventually set mouse down on the mouseup event.

`mouseDown = false;`

when setting a variable in javascript it will first search the scope for the variable and use that if it finds it.
when it does not find the variable, it first throws a ReferenceError and then declares that variable to be global. The rest of your application can then see the global variable called "mouseDown" and uses it.

I think a possible reason that JavaScript does that is because some application when deployed to production might run into this error. JavaScript is trying to apply a temporary fix to it in order for the application to work until the developers fix the issue.

fix the capitalization, commit, and close this issue

**Comment by micahpotts** [comment]
Fixed!
